Add github actions
ITMO-NSS-team/GOLEM pull request #5
Opened 2022-12-13 09:04 UTC by YamLyubov

WIP

2022-12-13 14:45 UTC, gkirgizov requested changes

2022-12-13 14:45 UTC, gkirgizov commented on .github/workflows/unit-build.yml
> +        pip install .[profilers]
мб тут теперь  нужно .[examples]?

2022-12-13 14:45 UTC, gkirgizov commented on README.rst
> +.. |build| image:: https://github.com/ITMO-NSS-team/GOLEM/actions/workflows/unit-build.yml/badge.svg?branch=master
branch не тот

2022-12-15 08:36 UTC, YamLyubov commented on .github/workflows/unit-build.yml
> +        pip install .[profilers]
Добавила

2022-12-15 08:37 UTC, YamLyubov commented on README.rst
> +.. |build| image:: https://github.com/ITMO-NSS-team/GOLEM/actions/workflows/unit-build.yml/badge.svg?branch=master
[Исправила](https://github.com/ITMO-NSS-team/GOLEM/pull/5/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR155)

2022-12-16 14:20 UTC, gkirgizov approved these changes

2022-12-16 14:20 UTC, merged